#lang scheme/gui
(define (frame-coord-map frame)
  (lambda (v) (add-vect
                        (origin-frame frame)
                        (add-vect (scale-vect (xcor-vect v)
                                              (edge1-frame frame))
                                  (scale-vect (ycor-vect v)
                                              (edge2-frame frame))))))
(define (make-vect x y) (cons x y))
(define (xcor-vect v) (car v))
(define (ycor-vect v) (cdr v))
(define (add-vect x y)
  (cons (+ (xcor-vect x) (xcor-vect y)) (+ (ycor-vect x) (ycor-vect y))))
(define (sub-vect x y)
  (cons (- (xcor-vect x) (xcor-vect y)) (- (ycor-vect x) (ycor-vect y))))
(define (scale-vect s a)
  (cons (* (xcor-vect a) s) (* (ycor-vect a) s)))
(define (make-frame origin edge1 edge2) (list origin edge1 edge2))
(define (origin-frame frame) (car frame))
(define (edge1-frame frame) (cadr frame))
(define (edge2-frame frame) (caddr frame))